<div id="zoom-parent">
	<img class="animation-image" id="default_image" src="img/zoom_animation/multi_touch_zoom_00000.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00001.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00002.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00003.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00004.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00005.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00006.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00007.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00008.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00009.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00010.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00011.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00012.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00013.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00014.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00015.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00016.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00017.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00018.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00019.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00020.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00021.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00022.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00023.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00024.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00025.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00026.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00027.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00028.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00029.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00030.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00031.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00032.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00033.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00034.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00035.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00036.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00037.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00038.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00039.jpg">
	<img class="animation-image" src="img/zoom_animation/multi_touch_zoom_00040.jpg">
</div> 